name: Deploy to S3

on:
  push:
    branches:
      - main   # runs when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AKIA3KHWWGW33T7ZPSF7 }}
          aws-secret-access-key: ${{ secrets.AwxuiRjcVqJkzKVRjUaoyZxTmPeLdGzVihjEU3iL }}
          aws-region: ${{ secrets.us-west-2 }}

      - name: Sync files to S3
        run: aws s3 sync ./ s3://${{ secrets.nkemjika }} --delete
